FROM mongo:4.4.4

COPY ./mongod.conf /etc/

# RUN apt-get update
# RUN apt-get install vim -y
# RUN apt-get install nano -y

RUN mkdir -pv ./data/db

EXPOSE 34982

# ENTRYPOINT ["mongod", "--config", "/etc/mongod.conf"]