FROM mongo:4.4.4

COPY ./mongod.conf /etc/
COPY ./node_modules ./node_modules
# RUN apt-get update
# RUN apt-get install vim -y
# RUN apt-get install nano -y

RUN mkdir -pv ./data/db

EXPOSE ${MONGO_PORT}
