version: "3.9"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    command: mongod --config /etc/mongod.conf --auth
    networks:
      - skillup-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - $PWD/mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped

  mongo-express:
    build:
      context: .
      dockerfile: Dockerfile_mongo-express
    networks:
      - skillup-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=user123
    volumes:
      - $PWD/mongo-data
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    # healthcheck:
    #   test:  wget --quiet --tries=3 --spider http://admin:admin123@0.0.0.0:8081 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped
  
volumes:
  mongo-data:

networks:
  skillup-network:
